//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int RoomId { get; set; }
        public Nullable<int> OrderStatusId { get; set; }
        public string Text { get; set; }
        public string Audio { get; set; }
        public int CountOfClient { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Room Room { get; set; }
    }
}
